routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace'=>'Client'],function(){
    Route::group(['namespace'=>'Home'],function(){
        Route::get('/','HomeCont@index')->name('home');
        Route::get('sTitle','HomeCont@titleList');
        Route::get('sIssn','HomeCont@issnList');
        Route::get('sSubject','HomeCont@subjectList');
        Route::get('sAuthor','HomeCont@authorList');
    });

    Route::group(['namespace'=>'Lists'],function(){
        Route::get('list','ListCont@index')->name('lists');
        Route::get('list/{id}','ListCont@detail')->name('detail');
        Route::get('download/{file_id}','ListCont@download')->name('download');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Pivot\LoanPivot;
use App\Traits\UuidForKey;
use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable,UuidForKey;
    public $incrementing = false;
    protected $appends = [
        'active_loan','done_loan','broken_loan','lost_loan'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ["id"];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function loans(){
        return $this->belongsToMany(Item::class,'loans','user_id','item_id')->using(LoanPivot::class)->wherePivot('loan_status_id',1)->withPivot([
            'loan_start','loan_end','loan_status_id','admin_id','id'
        ]);
    }

    public function returned(){
        return $this->belongsToMany(Item::class,'loans','user_id','item_id')->using(LoanPivot::class)->wherePivot('loan_status_id',2);
    }

    public function getActiveLoanAttribute(){
        $id = $this->id;
        return (new Loan())->whereHas('user',function($model) use ($id){
            $model->where('id',$id);
        })->where('loan_status_id',1)->count();
    }

    public function getDoneLoanAttribute(){
        $id = $this->id;
        return (new Loan())->whereHas('user',function($model) use ($id){
            $model->where('id',$id);
        })->where('loan_status_id',2)->count();
    }

    public function getBrokenLoanAttribute(){
        $id = $this->id;
        return (new Loan())->whereHas('user',function($model) use ($id){
            $model->where('id',$id);
        })->where('loan_status_id',3)->count();
    }

    public function getLostLoanAttribute(){
        $id = $this->id;
        return (new Loan())->whereHas('user',function($model) use ($id){
            $model->where('id',$id);
        })->where('loan_status_id',4)->count();
    }

    public function getLateLoanAttribute(){
        $id = $this->id;
        $now = Carbon::now()->format('Y-m-d H:i:s');

        return (new Loan())->whereHas('user',function($model) use ($id,$now){
            $model->where('id',$id);
        })->where('loan_status_id',1)->where('loan_end','<',$now)->count();
    }
}

app/Http/Controllers/Wandx/Circulation/CirculationCont.php
<?php

namespace App\Http\Controllers\Wandx\Circulation;

use App\Models\Collection;
use App\Models\Item;
use App\Models\ItemStatus;
use App\Models\Loan;
use App\Models\Location;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CirculationCont extends Controller
{
    public function index(Request $request,Item $item,ItemStatus $status,Location $location){
        $data = [
            'lists' => $this->itemQuery($request,$item),
            'status' => $status->newQuery()->pluck('status','id')->toArray(),
            'lokasi' => $location->newQuery()->pluck('name','id')->toArray(),
        ];

        return view('wandx.sirkulasi.index',$data);
    }

    public function detail($id,Item $item){
        $data = [
            'item' => $item->newQuery()->find($id)
        ];
        return view('wandx.sirkulasi.detail',$data);
    }

    public function pinjam(Request $request,Loan $loan,Item $item){
        $userid = getNimById($request->input('nis'));

        if($userid == null){
            return redirect()->back()->with(['failed'=>'NIS tidak ditemukan']);
        }
        $data = [
            'loan_start' => Carbon::parse($request->input('in'))->format('Y-m-d H:i:s'),
            'loan_end' => Carbon::parse($request->input('ret'))->format('Y-m-d H:i:s'),
            'item_id' => $request->input('item-id'),
            'user_id' => $userid,
            'admin_id' => auth('admin')->user()->id,
            'loan_status_id' => 1
        ];

        $loan->newQuery()->create($data);
        $item->newQuery()->find($request->input('item-id'))->update([
            'status_id' => 2
        ]);

        return redirect()->back();
    }

    public function kembali(Request $request,Loan $loan,Item $item){
        $loan_id = $request->input('loan-id');
        $item_id = $request->input('item-id');

        $loan->newQuery()->find($loan_id)->update([
            'loan_status_id' => 2
        ]);

        $item->newQuery()->find($item_id)->update(['status_id'=>4]);
        return redirect()->back();
    }

    public function keRak(Request $request,Item $item){
        $item->newQuery()->find($request->input('item-id'))->update(['status_id'=>1]);
        return redirect()->back();
    }

    public function titleList(Request $request,Collection $collection){
        return $collection->newQuery()->where('title','like','%'.$request->input('query').'%')->pluck('title');
    }

    public function issnList(Request $request,Collection $collection){
        return $collection->newQuery()->where('code','like','%'.$request->input('query').'%')->pluck('code');
    }

    public function codeList(Request $request,Item $item){
        return $item->newQuery()->where('code','like','%'.$request->input('query').'%')->pluck('code');
    }

    public function pubList(Request $request,Collection $collection){
        return $collection->newQuery()->where('pub','like','%'.$request->input('query').'%')->pluck('pub');
    }

    public function subjectList(Request $request,Collection $collection){
        return $collection->newQuery()->where('subject','like','%'.$request->input('query').'%')->pluck('subject');
    }

    public function nislist(Request $request,User $user){
//        return $user->newQuery()->get();
        return $user->newQuery()->where('nim','like','%'.$request->input('query').'%')->pluck('nim');
    }

    public function getUserByNis($nis,User $user){
        $data = [
            'user' => $user->newQuery()->where('nim',$nis)->first()
        ];

        return view('wandx.sirkulasi.info_siswa',$data);
    }

    private function itemQuery(Request $request,Item $item){
        $c = $item->newQuery();

        if($request->has('code')){
            $c->where('code',$request->input('code'));
        }

        if($request->has('issn')){
            $c->whereHas('collection',function($model) use ($request){
                $model->where('code',$request->input('issn'));
            });
        }

        if($request->has('judul')){
            $c->whereHas('collection',function($model) use ($request){
                $model->where('title','like','%'.$request->input('judul').'%');
            });
        }

        if($request->has('penerbit')){
            $c->whereHas('collection',function($model) use ($request){
                $model->where('pub','like','%'.$request->input('penerbit').'%');
            });
        }

        if($request->has('lokasi')){
            $c->where('location_id',$request->input('lokasi'));
        }

        if($request->has('status')){
            $c->where('status_id',$request->input('status'));
        }

        $c->orderBy('created_at','asc');

        return $c->paginate(10);
    }
}

app/Http/Controllers/Wandx/Collection/CollectionCont.php
<?php

namespace App\Http\Controllers\Wandx\Collection;

use App\Models\Collection;
use App\Models\CollectionType;
use App\Models\File;
use App\Models\Item;
use App\Models\ItemStatus;
use App\Models\Location;
use App\Models\MediaType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Yajra\Datatables\Datatables;

class CollectionCont extends Controller
{
    public function index(Request $request,Collection $collection){
        $data = [
            'lists' => $this->collectionQuery($request,$collection)
        ];

        return view('wandx.collection.index',$data);
    }

    private function collectionQuery(Request $request,Collection $collection){
        $c = $collection->newQuery();



        if($request->has('code')){
            $c->where('code',$request->input('code'));
        }

        if($request->has('judul')){
            $c->where('title',"like","%".$request->input('judul')."%");
        }

        if($request->has('penerbit')){
            $c->where('pub',$request->input('penerbit'));
        }

        if($request->has('subyek')){
            $c->where('subject',$request->input('subyek'));
        }

//        $c->orderBy('created_at','desc');

        return $c->latest()->paginate(10);
    }

    public function add(CollectionType $collectionType){
        $data = [
            'category' => $collectionType->newQuery()->pluck('name','id'),
        ];
        return view("wandx.collection.add",$data);
    }

    public function edit($id,Collection $collection,MediaType $mediaType,CollectionType $collectionType,ItemStatus $itemStatus,Location $location){
        $data = [
            'collection' => $collection->newQuery()->find($id),
            'media' => $mediaType->newQuery()->pluck('name','id'),
            'category' => $collectionType->newQuery()->pluck('name','id'),
            'status' => $itemStatus->newQuery()->pluck('status','id'),
            'location' => $location->newQuery()->pluck('name','id')
        ];
        return view('wandx.collection.edit',$data);
    }

    public function getItem($id,Item $item,ItemStatus $status,MediaType $mediaType,Location $location){
        $data = [
            'item' => $item->newQuery()->find($id),
            'status' => $status->newQuery()->pluck('status','id'),
            'media' => $mediaType->newQuery()->pluck('name','id'),
            'location' => $location->newQuery()->pluck('name','id')
        ];

        return view('wandx.collection.modal_edit_item',$data);
    }

    public function storeItem(Request $request,Item $item){
        $data = [
            'code' => $request->input('code'),
            'status_id' => $request->input('status_id'),
            'media_type_id' => $request->input('media_type_id'),
            'collection_id' => $request->input('collection-id'),
            'location_id' => $request->input('location_id'),
            'no_rak' => $request->input('no_rak')
        ];

        $store = $item->newQuery()->create($data);

        if($request->hasFile('file')){
            $name = $request->input('code').'_'.str_random(6).'.'.$request->file('file')->extension();
            $path = storage_path('files');
            $request->file('file')->move($path,$name);
            $fileData = [
                'filename' => $name,
                'path' => $path,
                'admin_id' => auth('admin')->user()->id,
                'item_id' => $store->id
            ];
            $store->file()->create($fileData);
        }
        return redirect()->back();

    }

    public function updateItem($id,Request $request,Item $item,File $files){
        $old = $item->newQuery()->find($id)->file;
        $data = [
            'code' => $request->input('code'),
            'status_id' => $request->input('status_id'),
            'media_type_id' => $request->input('media_type_id'),
            'location_id' => $request->input('location_id'),
            'no_rak' => $request->input('no_rak')
        ];

        $item->newQuery()->find($id)->update($data);



        if($request->hasFile('file')){
            if($old != null){
                try{
                    \File::delete($old->path.$old->filename);
                }catch (\Exception $exception){}
            }
            $name = $request->input('code').'_'.str_random(6).'.'.$request->file('file')->extension();
            $path = storage_path('files');
            $request->file('file')->move($path,$name);
            $fileData = [
                'filename' => $name,
                'path' => $path,
                'admin_id' => auth('admin')->user()->id,
                'item_id' => $id
            ];
            $files->newQuery()->updateOrCreate(['item_id'=>$id],$fileData);
        }
        return redirect()->back();
    }

    public function deleteFile($id,File $file){
        $file->newQuery()->find($id)->delete();
    }

    public function delete_item($id,Item $item){
        $item->newQuery()->find($id)->delete();
        return redirect()->back();
    }

    public function store(Request $request,Collection $collection){
        $data = [
            "title" => $request->input("title"),
            "subtitle" => $request->input("subtitle"),
            "collection_type_id" => $request->input("collection_type_id"),
            "code" => $request->input("code"),
            "type" => $request->input("type"),
            "language" => $request->input("language"),
            "pub" => $request->input("pub"),
            "pub_year" => $request->input("pub_year"),
            "pub_city" => $request->input("pub_city"),
            "desc" => $request->input("desc"),
            "authors" => $request->input("authors"),
            "subject" => $request->input("subject")
        ];

        $store = $collection->create($data);
        return redirect()->route("adm.collection.edit",["id"=>$store->id]);
    }

    public function update($id,Request $request,Collection $collection){
        $data = [
            "title" => $request->input("title"),
            "subtitle" => $request->input("subtitle"),
            "collection_type_id" => $request->input("collection_type_id"),
            "code" => $request->input("code"),
            "type" => $request->input("type"),
            "language" => $request->input("language"),
            "pub" => $request->input("pub"),
            "pub_year" => $request->input("pub_year"),
            "pub_city" => $request->input("pub_city"),
            "desc" => $request->input("desc"),
            "authors" => $request->input("authors"),
            "subject" => $request->input("subject")
        ];

        $store = $collection->newQuery()->find($id)->update($data);
        return redirect()->back();
    }

    public function destroy($id,Collection $collection){
        $collection->newQuery()->find($id)->delete();
        return redirect()->back();
    }

    public function getData($id,Collection $collection){}

    public function titleList(Request $request,Collection $collection){
        return $collection->newQuery()->where('title','like','%'.$request->input('query').'%')->pluck('title');
    }

    public function issnList(Request $request,Collection $collection){
        return $collection->newQuery()->where('code','like','%'.$request->input('query').'%')->pluck('code');
    }

    public function pubList(Request $request,Collection $collection){
        return $collection->newQuery()->where('pub','like','%'.$request->input('query').'%')->pluck('pub');
    }

    public function subjectList(Request $request,Collection $collection){
        return $collection->newQuery()->where('subject','like','%'.$request->input('query').'%')->pluck('subject');
    }
}

app/Http/Controllers/Wandx/Dashboard/DashboardCont.php
<?php

namespace App\Http\Controllers\Wandx\Dashboard;

use App\Models\Collection;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardCont extends Controller
{
    public function index(){
        $data = [
            "collection" => (new Collection())->count(),
            "user" => (new User())->count()
        ];
        return view('wandx.dashboard.index',$data);
    }
}

app/Http/Controllers/Wandx/Usermanager/RoleCont.php
<?php

namespace App\Http\Controllers\Wandx\Usermanager;

use App\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleCont extends Controller
{
    public function index(Role $role){
        $data = [
            'roles' => $role->newQuery()->get()
        ];

        return view('wandx.usermanager.role',$data);

    }

    public function menuIds($role_id,Role $role){
        $cek = $role->newQuery()->find($role_id);

        if($cek->menus->count() > 0){
            return $cek->menus->pluck('id');
        }

        return [];
    }

    public function updateMenu(Request $request,Role $role){
        $role_id = $request->input('role_id');
        $role->newQuery()->find($role_id)->menus()->sync($request->input('menus'));
        return redirect()->back()->with(['success'=>'Saved']);
    }

    public function removeAccess($id,$role_id,Role $role){
        $role->newQuery()->find($role_id)->menus()->detach($id);
    }
}

resources/views/wandx/siswa/add.blade.php
@extends('wandx.master')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="#">Siswa</a></li>
        <li><a href="#">Add</a></li>
    </ol>
@stop

@section('page-header')
    <h1>
        Add Siswa
        <small>Add siswa</small>
    </h1>
@stop

@section('contents')
    <div class="panel">
        <div class="panel-body">
            {!! Form::open(["class"=>"form-horizontal"]) !!}
            <div class="form-group">
                <label for="nis" class="col-sm-3 control-label">NIS</label>
                <div class="col-sm-7">
                    <input required type="text" class="form-control" id="nis" name="nim">
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-sm-3 control-label">Name</label>
                <div class="col-sm-7">
                    <input required type="text" class="form-control" id="name" name="name">
                </div>
            </div>

            <div class="form-group">
                <label for="address" class="col-sm-3 control-label">Address</label>
                <div class="col-sm-7">
                    <input required type="text" class="form-control" id="address" name="address">
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Email</label>
                <div class="col-sm-7">
                    <input required type="text" class="form-control" id="email" name="email">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 text-right">
                    <button class="btn btn-primary">Save</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('modals')

@stop

@section('scripts')

@stop

resources/views/wandx/siswa/edit.blade.php
@extends('wandx.master')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="#">Siswa</a></li>
        <li><a href="#">Edit</a></li>
    </ol>
@stop

@section('page-header')
    <h1>
        Edit Siswa
        <small>Edit siswa</small>
    </h1>
@stop

@section('contents')
    <div class="panel">
        <div class="panel-body">
            {!! Form::model($user,["class"=>"form-horizontal"]) !!}
            <div class="form-group">
                <label for="nis" class="col-sm-3 control-label">NIS</label>
                <div class="col-sm-7">
                    <input value="{{ $user->nim }}" required type="text" class="form-control" id="nis" name="nim">
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-sm-3 control-label">Name</label>
                <div class="col-sm-7">
                    <input  value="{{ $user->name }}" required type="text" class="form-control" id="name" name="name">
                </div>
            </div>

            <div class="form-group">
                <label for="address" class="col-sm-3 control-label">Address</label>
                <div class="col-sm-7">
                    <input value="{{ $user->address }}" required type="text" class="form-control" id="address" name="address">
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Email</label>
                <div class="col-sm-7">
                    <input value="{{ $user->email }}" required type="text" class="form-control" id="email" name="email">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 text-right">
                    <button class="btn btn-primary">Save</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('modals')

@stop

@section('scripts')

@stop

resources/views/wandx/siswa/index.blade.php
@extends('wandx.master')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li><a href="#">Siswa</a></li>
    </ol>
@stop

@section('page-header')
    <h1>
        Siswa
        <small>Daftar siswa yang menjadi anggota perpustakaan</small>
    </h1>
@stop

@section('contents')
    <div class="panel">
        <div class="panel-body">
            <table class="table table-bordered table-hover" id="user-table">
                <thead>
                <tr>
                    <th rowspan="2">NIS</th>
                    <th rowspan="2">Nama</th>
                    <th rowspan="2">Alamat</th>
                    <th colspan="5">Status pinjaman</th>
                    <th rowspan="2">Aksi</th>
                </tr>
                <tr>
                    <th>Aktif</th>
                    <th>Terlambat</th>
                    <th>Selesai</th>
                    <th>Rusak</th>
                    <th>Hilang</th>
                </tr>

                </thead>
                <tbody>
                    @forelse($lists as $list)
                        <tr>
                            <td>{{ $list->nim }}</td>
                            <td>{{ $list->name }}</td>
                            <td>{{ $list->address }}</td>
                            <td class="text-center">{{ $list->active_loan }}</td>
                            <td class="text-center">{{ $list->late_loan }}</td>
                            <td class="text-center">{{ $list->done_loan }}</td>
                            <td class="text-center">{{ $list->broken_loan }}</td>
                            <td class="text-center">{{ $list->lost_loan }}</td>
                            <td class="text-center">
                                <a href="{{ route('adm.siswa.edit',['id'=>$list->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a>
                                <a href="{{ route('adm.siswa.delete',['id'=>$list->id]) }}" onclick="return confirm('Are you sure?')" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                        @empty
                    @endforelse
                </tbody>
            </table>
            <div class="text-center">
                {{ $lists->render() }}
            </div>
        </div>
    </div>
@stop

@section('modals')

@stop

@section('scripts')

@stop

@section('styles')
    <style>
        table.table#user-table tr th{
            vertical-align: middle;
            text-align: center;
        }
    </style>
    
@stop